# Generated by Django 4.2.13 on 2024-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('graduation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
